### ISSUE TITLE
安装依赖包 > unzip qrencode失败

### ISSUE THREAD

**Issue by zhangyiw** [233boy/Xray#2]
12:33:56) 下载 Xray 脚本 > https://github.com/233boy/xray/releases/latest/download/code.zip
12:33:56) 安装依赖包 > unzip qrencode
12:34:01) 安装依赖包失败
12:34:01) 哦豁..
12:34:01) 安装过程出现错误...

root@heallen:~ # uname -a
Linux heallen 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1 (2017-12-23) x86_64 GNU/Linux
root@heallen:~ # cat /etc/debian_version
9.13
root@heallen:~ # cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 9 (stretch)"
NAME="Debian GNU/Linux"
VERSION_ID="9"
VERSION="9 (stretch)"
VERSION_CODENAME=stretch
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by 233boy** [comment]
@zhangyiw 换 Ubuntu 22
