### ISSUE TITLE
建议调整reality默认指纹

### ISSUE THREAD

**Issue by AgathonLi** [233boy/Xray#31]
您好，脚本一键安装后reality指纹是ios，但好像没有调整的选项。指纹是ios其实会有点奇怪吧，毕竟它只有手机端。如果将默认指纹调整为chrome是否会更好？谢谢

**Comment by 233boy** [comment]
@AgathonLi 

这个是客户端可选项的，你可以在客户端这边随便选择一个就行，显示用 ios 是因为有些人说这个更好一些，不过可能是玄学

**Comment by AgathonLi** [comment]
好的

> @AgathonLi
> 
> 这个是客户端可选项的，你可以在客户端这边随便选择一个就行，显示用 ios 是因为有些人说这个更好一些，不过可能是玄学

好的，谢谢解答
