### ISSUE TITLE
自带了acme？

### ISSUE THREAD

**Issue by zhaosiyu2010** [233boy/Xray#42]
xray add vws vvpn.qyzhao.cn
按上面命令配置的话，acme可以自动申请证书？
三个月到期会自动更换嘛？

**Comment by zhaosiyu2010** [comment]
还有个问题，可以访问google了，但不能同时访问blog.csdn.net

**Comment by 233boy** [comment]
@zhaosiyu2010 

自动更新的不用管，是 caddy 实现的。

不要全开局，默认屏蔽了国内 IP

**Comment by zhaosiyu2010** [comment]
您好，我已收到您的邮件，会尽快给您回复。或者您可通过一下方式联系我:

Mobile:13918123493E-mail:Add:上海市普陀区礼尚路69号高逸尚城T3办公楼11-12层

**Comment by zhaosiyu2010** [comment]
3q



***@***.***
 
发件人： 233boy
发送时间： 2023-12-02 22:45
收件人： 233boy/Xray
抄送： 赵前禹; Mention
主题： Re: [233boy/Xray] 自带了acme？ (Issue #42)
@zhaosiyu2010
自动更新的不用管，是 caddy 实现的。
不要全开局，默认屏蔽了国内 IP
