### ISSUE TITLE
怎么不屏蔽大陆ip？

### ISSUE THREAD

**Issue by fzxlzy** [233boy/Xray#46]
怎么不屏蔽大陆ip？

**Comment by 233boy** [comment]
@fzxlzy 

/etc/xray/config.json 里面有规则，ban_geoip_cn 那组规则 删除

**Comment by redstoneleo** [comment]
我就问一下为什么会有这个？什么原因？
      {
        "type": "field",
        "ip": [
          "geoip:cn"
        ],
        "marktag": "ban_geoip_cn",
        "outboundTag": "block"
      },
