### ISSUE TITLE
reality 模式没法连接

### ISSUE THREAD

**Issue by ouzc12358** [233boy/Xray#5]
配置完成后reality的测试通讯超时，换了几个vps 都是一样的情况。

**Comment by AleDaDa** [comment]
+1
默认的可以， 以前cdn+ws的不行， reality 也不行

**Comment by AleDaDa** [comment]
搞定了, 是cf 上面的加密要改成完全模式, 以前只有client -- cf 加密,  cf --vps 没有

**Comment by ouzc12358** [comment]
是SSL/TLS这边设置吗？我已经是完全了
还是完全（严格）？

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
