### ISSUE TITLE
可否新增配置备注功能

### ISSUE THREAD

**Issue by avsba001** [233boy/Xray#50]
例如：我新增了3个配置
![截图_20240120132514](https://github.com/233boy/Xray/assets/29015932/f02601f6-9037-4eef-8926-6b45c48b3c71)
能否在对应线路后面显示备注，实在记不清哪个配置在哪台设备了。
我就是1号配置http代理，sorarr之类的影视软件通过http出国
2号配置电脑用
3号配置手机用
哪天增减下配置协议都忘了- -

**Comment by 233boy** [comment]
@avsba001 不同的配置有不同的名字，相同的配置还有不同端口呀 😂

**Comment by avsba001** [comment]
> @avsba001 不同的配置有不同的名字，相同的配置还有不同端口呀 😂
就和nginx反代本地端口多了一样，万年不能录看一眼，时间长了就忘了。要么整个记事本记下对应哪个服务，要么整个导航页去了，有点槽- -。

以前觉得没各类东西没备注还好，现在学的东西上来了才发现问题0)

**Comment by 233boy** [comment]
@avsba001 
如果是万年不动的，你可以到 /etc/xray/conf 这里更改配置的名字（就当是备注 了

**Comment by avsba001** [comment]
感谢，这样也行
