### ISSUE TITLE
ChatGPT 无法刷新出历史聊天记录

### ISSUE THREAD

**Issue by 1747672002** [233boy/Xray#62]
使用xray脚本的 vless grpc 搭建的代理，使用 ChatGPT 无法刷新出历史聊天记录，多个协议都尝试了都不行，换了一个脚本就可以了，不知道什么原因

**Comment by 233boy** [comment]
@1747672002 玄学

**Comment by 1747672002** [comment]
> @1747672002 玄学
感谢大佬的回复，我也不知道什么情况，我试试联系下GPT的客服看看能不能解决
