### ISSUE TITLE
貌似不能打开chatgpt的网站

### ISSUE THREAD

**Issue by fg1157601129** [233boy/Xray#8]
貌似不能打开chatgpt的网站，其他的网站暂时没发现异常

**Comment by fg1157601129** [comment]
![image](https://github.com/233boy/Xray/assets/33218737/df33d827-a84d-430a-b8e2-2b37ea1fb203)

**Comment by 233boy** [comment]
@fg1157601129 

更改 /etc/xray/config.json 把那个 geoip:private 删除掉然后重启 xray 看看

看这个 #7

**Comment by fg1157601129** [comment]
已解决；删掉后重启就正常了。感谢大佬解答~
